# Uses original Johnson SG2Im model with meta learning
# For training on berkley deep drive

seed: 1
gpu: 0
meta: 1


# DATA OPTIONS
dataset: bdd
coco_train_image_dir: /path_to_bdd100k_dataset/bdd100k/images/100k/train
coco_val_image_dir: /path_to_bdd100k_dataset/bdd100k/images/100k/train
meta_base_dst_path: /path_to_bdd_labels/BDD_labels/
coco_no_mask: True

output_dir: checkpoints_migs_crn_bdd/
num_iterations: 120000
log_dir: runs/migs_crn_bdd
restore_from_checkpoint: 1
batch_size: 16
image_size:  !!python/tuple [128, 256]
checkpoint_every: 1000
eval_every: 3000
layout_size: !!python/tuple [32, 32]

use_crn: True


path_to_tmp_fid: fid/migs_crn_bdd

# meta learning
learning_rate: 0.0001
meta_learning_rate: 1
meta_inner_epochs: 10

# We are not sure if we need it at all
eval_mode_after: 40000