# Sg2im with SPADE and multi scale discriminator
# Trained on Bdd100k datase

seed: 1
gpu: 0

# DATA OPTIONS
dataset: bdd
coco_train_image_dir: /path_to_bdd100k_dataset/bdd100k/images/100k/train
coco_val_image_dir: /path_to_bdd100k_dataset/bdd100k/images/100k/train
coco_train_instances_json: /path_to_bdd_labels/BDD_labels//bdd100k_meta_train.json
coco_val_instances_json: /path_to_bdd_labels/BDD_labels//bdd100k_meta_val.json
coco_no_mask: True
output_dir: checkpoints_sg2im_spade_bdd/
num_iterations: 200000
log_dir: runs/sg2im_spade_bdd
restore_from_checkpoint: 1
batch_size: 8
image_size:  !!python/tuple [128, 256]
checkpoint_every: 2000
layout_size: !!python/tuple [32, 32]

# Losses weights
percept_weight: 5

# Spade options
spade_gen_blocks: True
multi_discriminator: True
discriminator_loss_weight: 1
d_obj_weight: 0.1
ac_loss_weight: 0.1
d_img_weight: 1
l1_pixel_loss_weight: 1
bbox_pred_loss_weight: 50
weight_change_after_50_iter: True
